---
apiVersion: batch/v1
kind: Job
metadata:
  name: profile-db-migration
  namespace: youlance
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: migration
          image: measri/youlance-profile:2.0
          env:
            - name: SKIP_DOCKER
              value: "1"
            - name: POSTGRES_ADDRESS
              value: profile-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: youlance_profiles
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: profile-db-user
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-db-user
                  key: db-pass
          command: ["./init_db.sh"]
      restartPolicy: Never
