---
apiVersion: batch/v1
kind: Job
metadata:
  name: profile-db-migration
  namespace: youlance
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: migration
          image: measri/youlance-profile:latest
          env:
            - name: SKIP_DOCKER
              value: "1"
            - name: PGADDRESS
              value: profile-db
            - name: PGPORT
              value: "5432"
            - name: PGNAME
              value: youlance_profiles
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: profile-db-user
                  key: db-user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-db-user
                  key: db-pass
          command: ["./init_db.sh"]
      restartPolicy: Never
