---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: youlance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: mehrddy/profileservice:1.0
          env:
            - name: APPPORT
              value: "80"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: profile-db-user
                  key: db-user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-db-user
                  key: db-pass
            - name: DB_ADDRESS
              value: user-db:5432
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: youlance
spec:
  selector:
    app: profile
  ports:
    - port: 80
      targetPort: 80
