---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: youlance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: measri/youlance-profile:2.0
          env:
            - name: APP_PORT
              value: "80"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: profile-db-user
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-db-user
                  key: db-pass
            - name: POSTGRES_ADDRESS
              value: profile-db
            - name: POSTGRES_DB
              value: youlance_profiles
            - name: POSTGRES_PORT
              value: "5432"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: youlance
spec:
  selector:
    app: profile
  ports:
    - port: 80
      targetPort: 80
