---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: youlance
type: Opaque
stringData:
  token-key: "12345678901234567890123456789012"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: youlance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mehdieidi/authservice-image:latest
          env:
            - name: SERVER_ADDRESS
              value: 0.0.0.0:80
            - name: REDIS_ADDR
              value: auth-db:6379
            - name: TOKEN_SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: token-key
            - name: VERIFY_SERVER_ADDR
              value: http://user/user/verify
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: youlance
spec:
  selector:
    app: auth
  ports:
    - port: 80
      targetPort: 80
