---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: youlance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: redis:7-alpine
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: youlance
spec:
  selector:
    app: auth-db
  ports:
    - port: 6379
      targetPort: 6379
