---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-files-pvc
  namespace: youlance
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  namespace: youlance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: vafatarighi/youlance-post:latest
          env:
            - name: APP_APPLICATION__PORT
              value: "80"
            - name: APP_DATABASE__HOST
              value: post-db
            - name: APP_DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: post-db-user
                  key: db-user
            - name: APP_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-db-user
                  key: db-pass
            - name: APP_DATABASE__DATABASE__NAME
              value: youlance_posts
          volumeMounts:
            - mountPath: /app/files
              name: files
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: post-files-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: post
  namespace: youlance
spec:
  selector:
    app: post
  ports:
    - port: 80
      targetPort: 80
