---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: youlance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: vafatarighi/youlance-ui:latest
          env:
            - name: NODE_URL
              value: http://localhost
            - name: NODE_PORT
              value: "80"
            - name: NODE_CLIENT_AUTH
              value: http://auth
            - name: NODE_CLIENT_USER
              value: http://user
            - name: NODE_CLIENT_PROFILE
              value: http://profile
            - name: NODE_CLIENT_POST
              value: http://post
            - name: NODE_CLIENT_FEED
              value: http://feed

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: youlance
spec:
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
