---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: youlance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: mehdieidi/userservice-image:latest
          env:
            - name: SERVER_ADDRESS
              value: 0.0.0.0:80
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-user
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: user-db-user
                  key: db-pass
            - name: DB_ADDRESS
              value: user-db:5432
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: youlance
spec:
  selector:
    app: user
  ports:
    - port: 80
      targetPort: 80
